name: Build Debian Package

on:
  pull_request:
    branches:
      - '**'  # Запуск при пуллреквестах из любой ветки

jobs:
  build_debian:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential debhelper python3-setuptools python3-pip

      - name: Build .deb package
        run: |
          mkdir -p debian_package/DEBIAN
          echo "Package: fastmodbuslibrary" > debian_package/DEBIAN/control
          echo "Version: 1.0" >> debian_package/DEBIAN/control
          echo "Architecture: all" >> debian_package/DEBIAN/control
          echo "Maintainer: Your Name <you@example.com>" >> debian_package/DEBIAN/control
          echo "Description: FastModbus library for Python" >> debian_package/DEBIAN/control

          mkdir -p debian_package/usr/local/lib/python3.8/dist-packages
          python3 -m pip install . --target=debian_package/usr/local/lib/python3.8/dist-packages

          dpkg-deb --build debian_package

      - name: Upload Debian artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: debian_package.deb
