name: Test and Build Debian Package

on:
  pull_request:
    branches:
      - '**'  # Запуск на любом pull request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          export PYTHONPATH="${{ github.workspace }}:${PYTHONPATH}"
          pytest tests/

  build:
    runs-on: ubuntu-latest
    needs: test  # Выполняется только после успешного прохождения тестов
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies for build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .deb package
        run: |
          mkdir -p debian_package/DEBIAN
          echo "Package: fastmodbuslibrary" > debian_package/DEBIAN/control
          echo "Version: 1.0" >> debian_package/DEBIAN/control
          echo "Section: base" >> debian_package/DEBIAN/control
          echo "Priority: optional" >> debian_package/DEBIAN/control
          echo "Architecture: all" >> debian_package/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> debian_package/DEBIAN/control
          echo "Description: Fast Modbus Python Library" >> debian_package/DEBIAN/control
          python setup.py install --root=debian_package/usr/local
          dpkg-deb --build debian_package

      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: debian_package.deb
