name: Build and Release

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        # Установка зависимостей для тестов
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Check Version in setup.py
      id: version_check
      run: |
        # Извлекаем версию из setup.py и передаем её дальше
        version=$(python setup.py --version)
        echo "Version from setup.py is $version"
        echo "::set-output name=version::$version"

    - name: Run Tests
      run: |
        # Запуск тестов, например с использованием pytest
        pytest tests/

    - name: Build Debian Package
      run: |
        # Сборка пакета, используя версию из setup.py
        echo "Building Debian package version ${{ steps.version_check.outputs.version }}..."
        # Предполагаем, что пакет будет назван с использованием версии, например:
        # dpkg-deb --build my_package/ debian_package_${{ steps.version_check.outputs.version }}.deb

    - name: Create Git Tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v${{ steps.version_check.outputs.version }} -m "Release version ${{ steps.version_check.outputs.version }}"
        git push origin v${{ steps.version_check.outputs.version }}

    - name: Release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: debian_package_${{ steps.version_check.outputs.version }}.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
