name: Build and Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest setuptools wheel

    - name: Install Package in Editable Mode
      run: |
        pip install -e .

    - name: Version Check
      id: version_check
      run: |
        version=$(python setup.py --version | tr -d '[:space:]')
        echo "Version is $version"
        echo "::set-output name=version::$version"

    - name: Run Tests
      run: pytest tests/

    - name: Build Debian Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        version=$(python setup.py --version | tr -d '[:space:]')
        echo "Building Debian package version $version..."
        echo "::set-output name=package_name::debian_package_${version}.deb"

  release:
    runs-on: ubuntu-latest
    needs: test_and_build
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Git Tag
      id: create_tag  # Добавлен id для передачи тега в релиз
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          version="prv${{ github.event.pull_request.number }}"
        else
          version="v${{ needs.test_and_build.outputs.version }}"
        fi
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "$version" -m "Release $version"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$version" --force
        echo "::set-output name=tag::$version"

    - name: Release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: debian_package_${{ needs.test_and_build.outputs.package_name }}
        tag_name: ${{ steps.create_tag.outputs.tag }}
        name: Release ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
