name: Build and Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Загружаем все теги для корректной проверки версии

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install setuptools wheel
        pip install -r requirements.txt
        pip install pytest

    - name: Install Package in Editable Mode
      run: |
        pip install -e .

    - name: Get Version from setup.py and Check for Update
      id: version_check
      run: |
        # Извлекаем текущую версию из setup.py
        current_version=$(python setup.py --version | tr -d '[:space:]')
        echo "Current version in setup.py: $current_version"

        # Извлекаем последнюю версию из тегов
        last_version=$(git describe --tags --abbrev=0 || echo "none")
        echo "Last version tag: $last_version"

        # Проверка на отсутствие тегов или на совпадение версии
        if [ "$last_version" == "none" ]; then
          echo "Error: No previous tags found. Make sure to tag versions properly."
          exit 1
        elif [ "$last_version" == "v$current_version" ]; then
          echo "Error: Version in setup.py ($current_version) has not been updated from the last release ($last_version)"
          exit 1
        fi

        # Устанавливаем выходную переменную для последующего использования
        echo "::set-output name=version::$current_version"

    - name: Run Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest tests/

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Загружаем все теги для доступа к версии

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies for Package Creation
      run: |
        pip install setuptools wheel
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm

    - name: Build Debian Package
      id: build_package
      run: |
        version="${{ needs.test.outputs.version }}"
        if [ -z "$version" ]; then
          echo "Error: Version is empty. Ensure that version is set correctly from setup.py."
          exit 1
        fi
        echo "Building Debian package version $version..."
        fpm -s python -t deb --python-bin python3 --name fastmodbuslibrary --version "$version" .
        echo "::set-output name=package_name::fastmodbuslibrary_${version}_all.deb"

    - name: Create Git Tag
      id: create_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version="${{ needs.test.outputs.version }}"
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          tag="prv${{ github.event.pull_request.number }}-v${version}"
          git push --delete origin "$tag" || true
          git tag -d "$tag" || true
        else
          tag="v${version}"
        fi
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "$tag" -m "Release $tag"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$tag" --force
        echo "::set-output name=tag::$tag"

    - name: Release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.build_package.outputs.package_name }}
        tag_name: ${{ steps.create_tag.outputs.tag }}
        name: "Release v${{ needs.test.outputs.version }}"
        draft: false
        prerelease: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
